version: '3'

volumes:
  postgres_data: {}

services:
  application:
    build:
      context: .
    image: auction_app
    ports:
      - 8000:8000
    depends_on:
      - postgres
    env_file:
      - compose.env

  postgres:
    image: postgres:14
    environment:
      POSTGRES_HOST: "postgres"
      POSTGRES_PORT: "5433"
      POSTGRES_DB: "auction"
      POSTGRES_USER: "auction"
      POSTGRES_PASSWORD: "auction"
    ports:
      - 9999:5433
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: -p 5433
